#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    BEGIN;
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_USER;
    GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $APP_USER;
    GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;
    COMMIT;
EOSQL
